server:
  port: 8989
spring:
  application:
    name: api-gateway
    loadbalancer:
      ribbon:
        enable: false
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${random.value}

app:
  user: damian