server:
  port: 0
spring:
  application:
    name: service1
  profiles:
    default: test1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${random.value}

app:
  user: damian